version: '3'

networks:
  sgc-net:
    driver: bridge

services:
  db:
    image: mysql:5.7
    container_name: sgc_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=sgc
      - MYSQL_DATABASE=sgcdb
      - MYSQL_USER=sgc
      - MYSQL_PASSWORD=sgc123
    networks:
      - sgc-net
  
  app:
    image: diegotesch/phplaravelcli:0.1
    container_name: sgc_api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    networks:
      - sgc-net
